# Generated by Django 6.0.1 on 2026-01-21 06:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("book", "Книга"),
                            ("movie", "Фильм"),
                            ("anime", "Аниме"),
                            ("series", "Сериал"),
                            ("game", "Игра"),
                            ("music", "Альбом"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Name media",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Name of work"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                        verbose_name="Rating (1-10)",
                    ),
                ),
                ("content", models.TextField(verbose_name="Review")),
                ("author", models.CharField(max_length=100, verbose_name="Author")),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(868),
                            django.core.validators.MaxValueValidator(2026),
                        ],
                        verbose_name="Year of release",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Рецензия",
                "verbose_name_plural": "Рецензии",
                "ordering": ["-created_at"],
            },
        ),
    ]
